# Complex Data Structures in Python
Welcome to this third part of introduction to python. We'll cover complex data structures including, lists, arrays, tuples and dictinnaries.

## Lists
Definition: A list is an ordered, mutable collection of items.
###  Characteristics:
- Ordered: Items maintain their position
- Mutable: Can change, add, or remove items
- Allows duplicates
- Indexed (starts at 0)
- Can contain mixed data types

In [1]:
# Creating lists
empty_list = []
from_range = list(range(5))
from_string = list("hello")

print("Empty:", empty_list)
print("From range:", from_range)
print("From string:", from_string)
type(empty_list)

Empty: []
From range: [0, 1, 2, 3, 4]
From string: ['h', 'e', 'l', 'l', 'o']


list

#### Exercise 1
Create a list called fruits containing "apple", "banana", "cherry", "date", "orange", "mango", "pears".
- Print the entire fruits list.
- Access and print the first element.
- Access and print the last element.
- Access and print "orange" using its index.
- Try to access an element at an invalid index and observe the error

In [19]:
# write your code here
fruits = ["apple", "banana", "cherry", "date", "orange", "mango", "pears"]
#for fruit in fruits:
#   print(fruit, end=' ')
print(fruits[0])
print(fruits[-1])
print(fruits[4])
fruits[7]

apple
pears
orange


IndexError: list index out of range

#### Slicing
Goal: built a new list from the orginal one

In [39]:
# example from exercise 1
#build a list starting from the third element
print(fruits[2:7])
#build a list containing only the third and the fourth elements
print(fruits[2:4])
#print the original list
print(fruits[4:])
print(len(fruits)-1)

['cherry', 'date', 'orange', 'mango', 'pears']
['cherry', 'date']
['orange', 'mango', 'pears']
7


#### List Modification
Common list methods for modification:

list.append(x): Add item at the end of the list.

list.insert(i, x): Insert an item at a given position.

list.remove(x): Removes the first item from the list with value x

list.pop(i): Remove item at position I and return it. If no index I is given then remove the first item in the list.

list.index(x): Return the index in the list of the first item with value x.

list.count(x): Return the number of time x appears in the list

list.sort(): Sorts items in the list in ascending order

list.reverse(): Reverses items in the list

#### Exercise 2
Given the list small_numbers defined as follows :
small_numbers = [10,20,30,40,50]
- Change the value of the second element to 25.
- Add 60 to the end of the list.
- Insert 5 at the beginning of the list.
- Remove 30 from the list.
- Print the list after each operation.
- Create the list of numbers as follows : large_numbers = [100,200,300,400,500]
- Concatenate small_numbers and large_numbers into a new list combined_list. Print it.
- Check if 30 is present in combined_list. Print the boolean result.
- Find the length of combined_list.
- Sort combined_list in descending order. Print it.

In [79]:
# write your code here
small_numbers = [10,20,30,40,30,50]
print("before",small_numbers)
small_numbers[1]=25
small_numbers.append(60)
small_numbers.insert(0,5)
small_numbers.remove(30)
print("after",small_numbers)
large_numbers = [100,200,300,400,500]
combined_list = small_numbers+large_numbers
#is_30_present=30 in combined_list
print(30 in combined_list)
print(combined_list)
len(combined_list)
combined_list.sort(reverse=True)
#combined_list.reverse()
print(combined_list)

before [10, 20, 30, 40, 30, 50]
after [5, 10, 25, 40, 30, 50, 60]
True
[5, 10, 25, 40, 30, 50, 60, 100, 200, 300, 400, 500]
[500, 400, 300, 200, 100, 60, 50, 40, 30, 25, 10, 5]


## Arrays
Arrays are similar to lists but Arrays  used to store multiple values having the same type.
### Characteristics
- Homogeneous, numerical, efficient for math
- Use for mathematical operations, large numerical datasets
Arrays are a part of the Python NumPy library.

In [81]:
# Example: 
import numpy as np
# 1D NumPy array
np_1d = np.array([1, 2, 3, 4, 5])
print(np_1d)
print("Type:", type(np_1d))
# Array operations (much faster than lists)
result = np_1d * 2 + 1
print("\nArray math:", result)

[1 2 3 4 5]
Type: <class 'numpy.ndarray'>

Array math: [ 3  5  7  9 11]


### 1D Array

In [83]:
#Creation of special arrays
arr1=np.arange(15) # Create an array starting from 0 to 15 (15 not included)
print(arr1)
arr2=np.arange(2, 3, 0.1) # Create an array of floats between 2 (inclusive) and 3 (exclusive) by a steps 0.1
print(arr2)
arr3=np.zeros(8)
print(arr3)
arr4=np.ones(8)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]


#### Exercise 3
Create a 1D array (list) called temperatures with values [22.5, 24.1, 23.8, 25.0, 21.9].
- Iterate through temperatures and print each value.
- Find and print the maximum temperature.
- Calculate and print the average temperature

In [91]:
# write your code here
temperatures = np.array([22.5, 24.1, 23.8, 25.0, 21.9])
for temp in temperatures:
    print(temp)
print(f" the max. temperature is {temperatures.max()}")
print(f" the avg. temperature is {temperatures.mean()}")

22.5
24.1
23.8
25.0
21.9
 the max. temperature is 25.0
 the avg. temperature is 23.46


#### Exercise 4
Given the following array : student_scores = [85,92,78,95,88]
- Ask the user to enter a score to search for. If found, print its index; otherwise, print the message "Score not found."
- Update the score of the third student (index 2) to 80. Print the updated student_scores.

In [108]:
# write your code here
student_scores = np.array([85,92,78,95,88,78])
score=int(input("please enter a score"))
indices=np.where(student_scores == score)[0]
if len(indices)!=0:
    print("index",indices[0])
else:
    print("score not found")

please enter a score 78


index [2 5]


#### Exercise 5
Create a 1D array called : data_points = [10,15,20,25,30,35]
- Calculate the sum of all data points.
- Count how many data points are greater than 20

In [ ]:
# write your code here
#HOMEWORK TWO VERSIONS / 1ST VERSION LIST : 2ND WITH NUMPY ARRAYS

### 2D Array

In [110]:
# Exemple of 2D NumPy array
np_2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
print(np_2d)
print("Shape:", np_2d.shape) # Matrix dimensions
print(type(np_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
<class 'numpy.ndarray'>


In [112]:
# matrix creation
m = np.array([[1, 2, 3],[4, 5, 6]])
print(m)
m1=np.zeros((6, 2)) # a matrix of zeros
print(m1)
m2=np.ones((2, 3)) # Define matrix of ones (1)
print(m2)

[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


#### Exercise 6
Create a 2D array (nested list) called matrix representing:
[[1,2,3],
 [4,5,6],
 [7,8,9]]
- Print the entire matrix.
- Access and print the element at row 0, column 1 (should be 2).
- Access and print the element at row 2, column 2 (should be 9).
- Iterate through matrix and print each element row by row.

In [127]:
# write your code here
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
print(matrix[0][1])
print(matrix[2][2])
for row in matrix:
    for element in row:
        print(element, end=' ')
    print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
1 2 3 
4 5 6 
7 8 9 


#### Exercise 7 (Matrix)
Given matrix_a = [[1, 2], [3, 4]] and matrix_b = [[5, 6], [7, 8]]
- Create a new result_matrix of the same dimensions, initialized with zeros.
- Perform element-wise addition of matrix_a and matrix_b, storing the results in result_matrix. Print result_matrix.

In [ ]:
# write your code here
#HOMEWORK

## Tuples
Tuple looks like a list but is immutable 
### Characteristics
- immutable : cannot be changed after creation
-  allows duplicate elements
-   heterogeneous data.

In [132]:
# Syntax
t1=() #empty tuple
print(t1)
t2=(4,)  #note the comma to differiante tuples from int
print(t2)
t3=True, 3.4, 18 # parenthesis are optional
print(t3)
t4=4, #note the comma to differiante tuples from int
print(t4)
type(t4)

()
(4,)
(True, 3.4, 18)
(4,)


tuple

In [134]:
# Creating tuples
empty_tuple = ()
from_list = tuple([1, 2, 3])
packing = 1, 2, 3  # Parentheses optional

print("Empty:", empty_tuple)
print("From list:", from_list)
print("Packing:", packing)

Empty: ()
From list: (1, 2, 3)
Packing: (1, 2, 3)


In [136]:
# Access and operations
person = ("Alice", 25, "Engineer")

print("Name:", person[0])
print("Age:", person[1])
print("Slice:", person[:2])

# Tuple unpacking

name, age, profession = person
print("Unpacked:", name, age, profession)

Name: Alice
Age: 25
Slice: ('Alice', 25)
Unpacked: Alice 25 Engineer


#### Exercise 8
Create a tuple called coordinates with values (10.5, 20.3).
- Print the entire coordinates tuple.
- Access and print the x-coordinate.
- Access and print the y-coordinate.
- Challenge: Try to change an element in coordinates and observe the error.

In [143]:
# write your code here
coordinates=(10.5, 20.3)
x,y=coordinates
print("x_coordinate ",x)
#coordinates[0]=10.3

x_coordinate  10.5


#### Exercise 9
Given a list of tuples students = [("Bob", 85), ("Charlie", 92), ("David", 78)].
- Iterate through students and print each student's name and score in a formatted string (e.g., "Bob scored 85").

In [145]:
# write your code here
students = [("Bob", 85), ("Charlie", 92), ("David", 78)]
for student in students:
    print(f"{student[0]} scored {student[1]}")

Bob scored 85
Charlie scored 92
David scored 78


### Unpacking

#### Exercise 10
Create a tuple person_info = ("Alice", 30, "New York").
- Unpack person_info into three variables: name, age, city. Print each variable.

In [ ]:
# write your code here
#HOMEWORK

#### Exercise 11
Create a function get_min_max(numbers) that takes a list of numbers and returns a tuple containing the minimum and maximum values. Test it with [5, 1, 9, 2, 7].

In [153]:
# write your code here
def get_min_max(numbers):
    minimum=min(numbers)
    maximum=max(numbers)
    return (maximum,minimum)
get_min_max([5, 1, 9, 2, 7])

(9, 1)

## Dictionaries
Unordered (in older Python versions, ordered from 3.7+), mutable, stores data in key-value pairs, keys must be unique and immutable, values can be any data type.
### Characteristics:
- Unordered (until Python 3.7+, now insertion ordered)
- Mutable: Can change, add, remove key-value pairs
- Keys must be unique and immutable
- Fast lookups by key

In [156]:
# Creating dictionaries
capitals = {
    "France": "Paris",
    "Germany": "Berlin", 
    "Italy": "Rome"
}
person = {"name": "Bob", "age": 30, "city": "New York"}

empty_dict = {}

print(capitals)
print(person)
print(empty_dict)
type(empty_dict)

{'France': 'Paris', 'Germany': 'Berlin', 'Italy': 'Rome'}
{'name': 'Bob', 'age': 30, 'city': 'New York'}
{}


dict

In [160]:
# Access
print("Name:", person["name"])
print("Age:", person.get("age"))
print("Country:",person["country"])
print("Country:", person.get("country", "Not specified")) # Safe access

Name: Bob
Age: 30


KeyError: 'country'

In [162]:
# Modification
person["age"] = 31                    # Update
person["country"] = "USA"             # Add new : When assigning to a key that does not exist ==> add a new entry
person.update({"job": "Engineer", "salary": 50000})  # Multiple updates

# Removal
removed_age = person.pop("age")       # Remove and return
del person["city"]                    # Remove without return

print("After operations:", person)
print("Removed age:", removed_age)

After operations: {'name': 'Bob', 'country': 'USA', 'job': 'Engineer', 'salary': 50000}
Removed age: 31


In [ ]:
# Iteration
# the key-value entry is called item in Python
print("\nKeys:", list(person.keys()))
print("Values:", list(person.values()))
print("Items:", list(person.items()))

print("\nLooping:")
for key in person.keys():
    print(f"key: {key}", end=' ')
print()
for value in person.values():
    print(f"value: {value}", end=' ')
print()
for key, value in person.items(): #item in dictionnaries is key:value
    print(f"  {key}: {value}")

#### Exercise 12
Create a dictionary called student_profile with the following key-value pairs:
"name": "Eve"
"age": 22
"major": "Computer Science"
"gpa": 3.8
- Print the entire student_profile dictionary.
- Access and print the student's name.
- Access and print the student's major.
- Try to access a non-existent key and observe the error.

In [170]:
# write your code here
student_profile = {"name": "Eve", "age": 22, "major": "Computer Science", "gpa": 3.8 }
print(student_profile)
print(student_profile["name"])
print(student_profile["major"])
student_profile["country"]

{'name': 'Eve', 'age': 22, 'major': 'Computer Science', 'gpa': 3.8}
Eve
Computer Science


KeyError: 'country'

#### Exercise 13
- Add a new key-value pair "university": "Tech University" to student_profile.
- Update the student's gpa to 3.9.
- Remove the "age" key-value pair from the dictionary.
- Iterate through student_profile and print all keys.
- Iterate through student_profile and print all values.
- Iterate through student_profile and print all key-value pairs.

In [ ]:
# write your code here
#homework

### Dictionary of Dictionaries

#### Exercise 14 
Create a dictionary library where keys are book titles and values are dictionaries containing "author" and "year".
Python
library = {
"The Great Gatsby": {"author": "F. Scott Fitzgerald", "year":1925 },
"1984": {"author": "George Orwell", "year":1949 }
}
- Access and print the author of "1984".
- Add a new book: "To Kill a Mockingbird", by "Harper Lee", published in 1960.
- Print all book titles and their respective authors.

In [180]:
# write your code here
library = { "The Great Gatsby": {"author": "F. Scott Fitzgerald", "year":1925 }, "1984": {"author": "George Orwell", "year":1949 } }
print(library["1984"]["year"])

1949
